// remote-detail-cart/src/App.vue
<template>
  <div class="py-8">
    <h1 class="text-3xl font-extrabold text-gray-900 tracking-tight mb-8">Your Cart</h1>
    
    <div v-if="cartItems.length === 0" class="bg-white p-8 text-center rounded-xl shadow-sm border border-gray-100">
      <p class="text-gray-500 text-lg">Your cart is empty.</p>
    </div>
    
    <div v-else class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
      <ul class="divide-y divide-gray-100">
        <li v-for="item in cartItems" :key="item.id" class="p-6 flex items-center justify-between">
          <div class="flex items-center gap-6">
            <img :src="item.image" :alt="item.name" class="w-20 h-20 object-cover rounded-lg" />
            <div>
              <h3 class="text-lg font-semibold text-gray-900">{{ item.name }}</h3>
              <p class="text-indigo-600 font-medium">${{ item.price }} x {{ item.quantity }}</p>
            </div>
          </div>
          <button @click="removeItem(item.id)" class="text-red-500 hover:text-red-700 font-medium transition-colors">
            Remove
          </button>
        </li>
      </ul>
      <div class="p-6 bg-gray-50 flex justify-between items-center border-t border-gray-100">
        <span class="text-xl font-bold text-gray-900">Total: ${{ total }}</span>
        <button @click="goToCheckout" class="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-lg font-semibold transition-colors">
          Proceed to Checkout
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue';
// @ts-ignore
import { cartStore, removeFromCart } from 'shared_store/store';

const cartItems = ref([]);
let unsubscribe = null;

onMounted(() => {
  const updateCart = (state) => {
    cartItems.value = state.items;
  };
  unsubscribe = cartStore.subscribe(updateCart);
  updateCart(cartStore.getState());
});

onUnmounted(() => {
  if (unsubscribe) unsubscribe();
});

const total = computed(() => {
  return cartItems.value.reduce((sum, item) => sum + (item.price * item.quantity), 0);
});

const removeItem = (id) => {
  removeFromCart(id);
};

const goToCheckout = () => {
  window.history.pushState({}, '', '/checkout');
  window.dispatchEvent(new Event('popstate'));
};
</script>

// remote-product/src/App.tsx
import React from "react";
// @ts-ignore
import { addToCart } from "shared_store/store";
import "./index.css";

const PRODUCTS = [
  { id: 1, name: "Premium Wireless Headphones", price: 299, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80", desc: "High quality wireless headphones with active noise cancellation." },
  { id: 2, name: "Mechanical Keyboard", price: 149, image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=400&q=80", desc: "RGB mechanical keyboard with tactile switches." },
  { id: 3, name: "Ergonomic Mouse", price: 89, image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=400&q=80", desc: "Comfortable ergonomic mouse designed for productivity." },
  { id: 4, name: "4K Monitor", price: 499, image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=400&q=80", desc: "Crisp 4K resolution monitor for creative professionals." },
];

const App = () => {
  return (
    <div className="py-8">
      <div className="flex justify-between items-end mb-8">
        <div>
          <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight">Latest Products</h1>
          <p className="mt-2 text-sm text-gray-500">Explore our premium selection of tech gear.</p>
        </div>
      </div>
      
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
        {PRODUCTS.map((product) => (
          <div key={product.id} className="bg-white rounded-xl shadow-sm hover:shadow-xl transition-shadow duration-300 overflow-hidden border border-gray-100 flex flex-col">
            <div className="h-48 overflow-hidden bg-gray-200">
              <img src={product.image} alt={product.name} className="w-full h-full object-cover hover:scale-105 transition-transform duration-500" />
            </div>
            <div className="p-5 flex-1 flex flex-col">
              <h3 className="text-lg font-semibold text-gray-900 mb-1 leading-tight">{product.name}</h3>
              <p className="text-sm text-gray-500 flex-1">{product.desc}</p>
              <div className="mt-4 flex items-center justify-between">
                <span className="text-xl font-bold text-indigo-600">${product.price}</span>
                <button 
                  onClick={() => addToCart(product)}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors focus:ring-4 focus:ring-indigo-100"
                >
                  Add to Cart
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default App;
